travis:
  secure:
    BINSTAR_TOKEN: iUaVVCGC+9jY6SaFil7ooloDGml3WSdOhbTlYppFwIlZ6kLQAQnCboGiOOKa7P9QOuMKH2Y5TGdKtNsstFr0muKo3RszFGKuQaiGtNL/PU+m0KPZsQWOI1IFPCQNFz5vGLGe7N2UkCV4OEQmas8YbJ521fEur/e2/KFifUiUyq/t94y+FIbxNz0qT0cqeIWiFU96u/oFnX3c0BaKJrgvBz1seKh64uYN4PuGMm13doSRAc9jgIMBUqqP3Jhl9ulcdP9fdZ7PwoJ8XsBpNxJO6wnh6NfL6t3hLzm221yYP3tpZ1ZbwkPFkJbPnshawqZ91NUo6oHBYFmlKuBL+HZIXZefgkrjK70g+dzHdQ80ORxoLTUADJkhf9DUFrS4X6qyu2bX3iQ5TPpA5wlJtDCAh2BNLQmqavEJ0ijvDs4jHoPv22tDA6ijMTMNTP98++rvM+iuMNhLw25oBSWiro0h6/6+7F+FtM0ejCYwZQwI5p7eLk8RMFAEA0Q4XTwk0djcCNF/ZjgMSHJXnc7J77eC/ABBazWSrAlNgxEgko0Ir9txBg44nPk64nZH6yi7TZ93ogSpcXkFIf+gyU7p1mI7wyENNMhyGhr4Acxok9sw18f13edc1mHJPQtoWa8SPcDS/kwqqodQaevjOpJYe/2XJ7Sxv9wFbY2Ob4Z3nNVeuMM=
conda_forge_output_validation: true
bot:
  automerge: true
